export const vehicles_offers = [
  {
    id: 1,
    image_url: "i10-hatchback.png",
    carroceria: "Hatchback",
    marca: "Hyundai",
    modelo: "i10 Hatch",
    precio: 10990,
    isOffer: true,
  },
  {
    id: 2,
    image_url: "i10-sedan.png",
    carroceria: "Sedan",
    marca: "Hyundai",
    modelo: "i10 Sedan",
    precio: 12290,
    isOffer: false,
  },
  {
    id: 3,
    image_url: "mazda2-sport.png",
    carroceria: "Hatchback",
    marca: "Mazda",
    modelo: "Mazda 2 Sport",
    precio: 16490,
    isOffer: true,
  },
  {
    id: 4,
    image_url: "mazda3-sedan.png",
    carroceria: "Sedan",
    marca: "Mazda",
    modelo: "Mazda 3 Sedan",
    precio: 23990,
    isOffer: false,
  },
  {
    id: 5,
    image_url: "new-accent.png",
    carroceria: "Sedan",
    marca: "Hyundai",
    modelo: "New Accent",
    precio: 16290,
    isOffer: true,
  },
  {
    id: 6,
    image_url: "new-santafe.png",
    carroceria: "SUV",
    marca: "Hyundai",
    modelo: "New Santa Fe",
    precio: 39990,
    isOffer: true,
  },
  {
    id: 7,
    image_url: "palisade.png",
    carroceria: "SUV",
    marca: "Hyundai",
    modelo: "New Palisade",
    precio: 47490,
    isOffer: true,
  },
  {
    id: 8,
    image_url: "tiggo8pro-gris.png",
    carroceria: "SUV",
    marca: "Chery",
    modelo: "Tiggo 8 Pro",
    precio: 24990,
    isOffer: true,
  },
];
