export const images_brands = [
  {
    id: 1,
    src: "BAIC_logo.png",
    alt: "Marca Baic",
    href: "baic",
  },
  {
    id: 2,
    src: "Chery_logo.png",
    alt: "Marca Chery",
    href: "chery",
  },
  {
    id: 3,
    src: "DFSK_logo.png",
    alt: "Marca DFSK",
    href: "dfsk",
  },
  {
    id: 4,
    src: "Geely_logo.png",
    alt: "Marca Geely",
    href: "geely",
  },
  {
    id: 5,
    src: "Glory_logo.png",
    alt: "Marca Glory",
    href: "glory",
  },
  {
    id: 6,
    src: "GWM_logo.png",
    alt: "Marca GWM",
    href: "great wall",
  },
  {
    id: 7,
    src: "Haval_logo.png",
    alt: "Marca Haval",
    href: "haval",
  },
  {
    id: 8,
    src: "Hyundai_logo.png",
    alt: "Marca Hyundai",
    href: "hyundai",
  },
  {
    id: 9,
    src: "JAC_logo.png",
    alt: "Marca JAC",
    href: "jac",
  },
  {
    id: 10,
    src: "JMC_logo.png",
    alt: "Marca JMC",
    href: "jmc",
  },
  {
    id: 11,
    src: "Mahindra_logo.png",
    alt: "Marca Mahindra",
    href: "mahindra",
  },
  {
    id: 12,
    src: "Mazda_logo.png",
    alt: "Marca Mazda",
    href: "mazda",
  },
  {
    id: 13,
    src: "Poer_logo.png",
    alt: "Marca Poer",
    href: "poer",
  },
  {
    id: 14,
    src: "Renault_logo.png",
    alt: "Marca Renault",
    href: "renault",
  },
  {
    id: 15,
    src: "Subaru_logo.png",
    alt: "Marca Subaru",
    href: "subaru",
  },
];
