import { iCardUbicanos } from "../CardLocal/CardLocal.props";

export const data_sedes: iCardUbicanos[] = [
  {
    id: 1,
    city: "chiclayo",
    sedeImage: "sai_boulevard_chiclayo.png",
    sedeName: "SAI Boulevard – Chiclayo",
    sedeAddress: "C.C. Boulevard: Av. Mariscal Nieto N°480",
    scheduleRegular: "8:30 a 18:30 horas",
    scheduleExtended: "8:30 a 14:00 horas",
    linkHowArrived: "https://maps.app.goo.gl/MxvztvSWQpqX2TY99",
  },
  {
    id: 2,
    city: "chiclayo",
    sedeImage: "sai_panamericana_chiclayo.png",
    sedeName: "SAI Panamericana – Chiclayo",
    sedeAddress: "Av. Panamericana N° 4200 - Ex fundo iris",
    scheduleRegular: "8:30 a 18:30 horas",
    scheduleExtended: "8:30 a 14:00 horas",
    linkHowArrived: "https://maps.app.goo.gl/vnTQYL9pQYYg9xui7",
  },
  {
    id: 3,
    city: "lima",
    sedeImage: "sai_angamos_surquillo.png",
    sedeName: "SAI Angamos – Surquillo",
    sedeAddress: "Av. Angamos N°1669 - Surquillo",
    scheduleRegular: "8:30 a 19:0 horas",
    scheduleExtended: "8:30 a 16:00 horas",
    linkHowArrived: "https://maps.app.goo.gl/scb4ux62GKWrpATy9",
  },
  {
    id: 4,
    city: "lima",
    sedeImage: "sai_ayacucho_surco.png",
    sedeName: "SAI Ayacucho – Surco",
    sedeAddress: "Av. Ayacucho N°126 – Surco",
    scheduleRegular: "8:30 a 19:00 horas",
    scheduleExtended: "8:30 a 16:00 horas",
    linkHowArrived: "https://maps.app.goo.gl/gHNcXnv2sokcQzCX8",
  },
  {
    id: 5,
    city: "trujillo",
    sedeImage: "sai_panamericana_chiclayo.png",
    sedeName: "SAI Cluster – Trujillo",
    sedeAddress: "Autopista Panamericana 1320 - Víctor Larco",
    scheduleRegular: "7:30 a 18:30 horas",
    scheduleExtended: "7:30 a 18:30 horas",
    linkHowArrived: "#",
  },
];
